/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/gseethar/Documents/Code/NIM/nim-0.14.2/lib -o /Users/gseethar/Documents/Code/GitHub/Learning/nim/nimcache/greeting.o /Users/gseethar/Documents/Code/GitHub/Learning/nim/nimcache/greeting.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell48505 Cell48505;
typedef struct Cellseq48521 Cellseq48521;
typedef struct Gcheap51018 Gcheap51018;
typedef struct Gcstack51016 Gcstack51016;
typedef struct Memregion30686 Memregion30686;
typedef struct Smallchunk30640 Smallchunk30640;
typedef struct Llchunk30680 Llchunk30680;
typedef struct Bigchunk30642 Bigchunk30642;
typedef struct Intset30614 Intset30614;
typedef struct Trunk30610 Trunk30610;
typedef struct Avlnode30684 Avlnode30684;
typedef struct Gcstat51014 Gcstat51014;
typedef struct Cellset48517 Cellset48517;
typedef struct Pagedesc48513 Pagedesc48513;
typedef struct Basechunk30638 Basechunk30638;
typedef struct Freecell30630 Freecell30630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc57002) (void);
struct  Cell48505  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48521  {
NI len;
NI cap;
Cell48505** d;
};
typedef Smallchunk30640* TY30701[512];
typedef Trunk30610* Trunkbuckets30612[256];
struct  Intset30614  {
Trunkbuckets30612 data;
};
struct  Memregion30686  {
NI minlargeobj;
NI maxlargeobj;
TY30701 freesmallchunks;
Llchunk30680* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30642* freechunkslist;
Intset30614 chunkstarts;
Avlnode30684* root;
Avlnode30684* deleted;
Avlnode30684* last;
Avlnode30684* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat51014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset48517  {
NI counter;
NI max;
Pagedesc48513* head;
Pagedesc48513** data;
};
struct  Gcheap51018  {
Gcstack51016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48521 zct;
Cellseq48521 decstack;
Cellseq48521 tempstack;
NI recgclock;
Memregion30686 region;
Gcstat51014 stat;
Cellset48517 marked;
Cellseq48521 additionalroots;
};
struct  Gcstack51016  {
Gcstack51016* prev;
Gcstack51016* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30640  {
  Basechunk30638 Sup;
Smallchunk30640* next;
Smallchunk30640* prev;
Freecell30630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30680  {
NI size;
NI acc;
Llchunk30680* next;
};
struct  Bigchunk30642  {
  Basechunk30638 Sup;
Bigchunk30642* next;
Bigchunk30642* prev;
NI align;
NF data;
};
typedef NI TY30619[8];
struct  Trunk30610  {
Trunk30610* next;
NI key;
TY30619 bits;
};
typedef Avlnode30684* TY30691[2];
struct  Avlnode30684  {
TY30691 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc48513  {
Pagedesc48513* next;
NI key;
TY30619 bits;
};
struct  Freecell30630  {
Freecell30630* next;
NI zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, TMP159)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc57002 markerproc0);
N_NIMCALL(NimStringDesc*, readline_15910_1689653243)(FILE* f0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell48505*, usrtocell_52640_1689653243)(void* usr0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_53801_1689653243)(Cell48505* c0);
N_NOINLINE(void, addzct_52617_1689653243)(Cellseq48521* s0, Cell48505* c0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, greetingInit000)(void);
NIM_EXTERNC N_NOINLINE(void, greetingDatInit000)(void);
STRING_LITERAL(TMP158, "Whats your name", 15);
STRING_LITERAL(TMP160, "Do not know name", 16);
STRING_LITERAL(TMP161, "name", 4);
STRING_LITERAL(TMP162, "Funny name is name", 18);
STRING_LITERAL(TMP163, "Hi, ", 4);
STRING_LITERAL(TMP164, "!", 1);
STRING_LITERAL(TMP165, "", 0);
STRING_LITERAL(TMP166, "Guru", 4);
STRING_LITERAL(TMP167, "Cool name", 9);
STRING_LITERAL(TMP179, "In set", 6);
STRING_LITERAL(TMP180, "either 3 or 8", 13);
STRING_LITERAL(TMP181, "Counting up ", 12);
NimStringDesc* name_109003_3201942695;
extern TNimType NTI138; /* string */
extern TFrame* frameptr_19836_1689653243;
extern Gcheap51018 gch_51058_1689653243;
NI value_109019_3201942695;
NI i_109037_3201942695;
N_NIMCALL(void, TMP159)() {
	nimGCvisit((void*)name_109003_3201942695, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19836_1689653243;
	frameptr_19836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19836_1689653243 = (*frameptr_19836_1689653243).prev;
}

static N_INLINE(Cell48505*, usrtocell_52640_1689653243)(void* usr0) {
	Cell48505* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell48505*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell48505*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell48505))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53801_1689653243)(Cell48505* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_52617_1689653243((&gch_51058_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell48505* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_52640_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell48505* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_52640_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_53801_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC11;
	int LOC13;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b0 == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = (NIM_BOOL)0;
	LOC11 = ((*a0).Sup.len == (*b0).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = (int)0;
	LOC13 = memcmp(((NCSTRING) ((*a0).data)), ((NCSTRING) ((*b0).data)), (*a0).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result0 = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_strutilsDatInit000();
	greetingDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_strutilsInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	greetingInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, greetingInit000)(void) {
	NimStringDesc* LOC18;
	nimfr("greeting", "greeting.nim")
	nimln(5, "greeting.nim");
	printf("%s\012", ((NimStringDesc*) &TMP158)? (((NimStringDesc*) &TMP158))->data:"nil");
	fflush(stdout);
nimRegisterGlobalMarker(TMP159);
	nimln(7, "greeting.nim");
	asgnRefNoCycle((void**) (&name_109003_3201942695), readline_15910_1689653243(stdin));
	nimln(8, "greeting.nim");
	{
		if (!((name_109003_3201942695) && (name_109003_3201942695)->Sup.len == 0)) goto LA3;
		nimln(9, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP160)? (((NimStringDesc*) &TMP160))->data:"nil");
		fflush(stdout);
	}
	goto LA1;
	LA3: ;
	{
		nimln(10, "greeting.nim");
		if (!eqStrings(name_109003_3201942695, ((NimStringDesc*) &TMP161))) goto LA6;
		nimln(11, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP162)? (((NimStringDesc*) &TMP162))->data:"nil");
		fflush(stdout);
	}
	goto LA1;
	LA6: ;
	{
		nimln(13, "greeting.nim");
		printf("%s%s%s\012", ((NimStringDesc*) &TMP163)? (((NimStringDesc*) &TMP163))->data:"nil", name_109003_3201942695? (name_109003_3201942695)->data:"nil", ((NimStringDesc*) &TMP164)? (((NimStringDesc*) &TMP164))->data:"nil");
		fflush(stdout);
	}
	LA1: ;
	nimln(15, "greeting.nim");
	if (eqStrings(name_109003_3201942695, ((NimStringDesc*) &TMP165))) goto LA9;
	if (eqStrings(name_109003_3201942695, ((NimStringDesc*) &TMP161))) goto LA10;
	if (eqStrings(name_109003_3201942695, ((NimStringDesc*) &TMP166))) goto LA11;
	goto LA12;
	LA9: ;
	{
		nimln(17, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP160)? (((NimStringDesc*) &TMP160))->data:"nil");
		fflush(stdout);
	}
	goto LA13;
	LA10: ;
	{
		nimln(19, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP162)? (((NimStringDesc*) &TMP162))->data:"nil");
		fflush(stdout);
	}
	goto LA13;
	LA11: ;
	{
		nimln(21, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP167)? (((NimStringDesc*) &TMP167))->data:"nil");
		fflush(stdout);
	}
	goto LA13;
	LA12: ;
	{
		nimln(23, "greeting.nim");
		printf("%s%s%s\012", ((NimStringDesc*) &TMP163)? (((NimStringDesc*) &TMP163))->data:"nil", name_109003_3201942695? (name_109003_3201942695)->data:"nil", ((NimStringDesc*) &TMP164)? (((NimStringDesc*) &TMP164))->data:"nil");
		fflush(stdout);
	}
	LA13: ;
	nimln(26, "greeting.nim");
	LOC18 = (NimStringDesc*)0;
	LOC18 = readline_15910_1689653243(stdin);
	value_109019_3201942695 = nsuParseInt(LOC18);
	nimln(27, "greeting.nim");
	switch (value_109019_3201942695) {
	case ((NI) 0) ... ((NI) 2):
	case ((NI) 4) ... ((NI) 7):
	{
		nimln(29, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP179)? (((NimStringDesc*) &TMP179))->data:"nil");
		fflush(stdout);
	}
	break;
	case ((NI) 3):
	case ((NI) 8):
	{
		nimln(31, "greeting.nim");
		printf("%s\012", ((NimStringDesc*) &TMP180)? (((NimStringDesc*) &TMP180))->data:"nil");
		fflush(stdout);
	}
	break;
	default:
	{
	}
	break;
	}
	nimln(36, "greeting.nim");
	printf("%s\012", ((NimStringDesc*) &TMP181)? (((NimStringDesc*) &TMP181))->data:"nil");
	fflush(stdout);
	{
		NI res_109043_3201942695;
		nimln(1875, "system.nim");
		res_109043_3201942695 = ((NI) 1);
		{
			nimln(1876, "system.nim");
			while (1) {
				NimStringDesc* LOC25;
				NI TMP182;
				if (!(res_109043_3201942695 <= ((NI) 10))) goto LA24;
				nimln(1877, "system.nim");
				i_109037_3201942695 = res_109043_3201942695;
				nimln(39, "greeting.nim");
				LOC25 = (NimStringDesc*)0;
				LOC25 = nimIntToStr(i_109037_3201942695);
				printf("%s\012", LOC25? (LOC25)->data:"nil");
				fflush(stdout);
				nimln(1891, "system.nim");
				TMP182 = addInt(res_109043_3201942695, ((NI) 1));
				res_109043_3201942695 = (NI)(TMP182);
			} LA24: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, greetingDatInit000)(void) {
}

