/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/gseethar/Documents/Code/NIM/nim-0.14.2/lib -o /Users/gseethar/Documents/Code/GitHub/Learning/nim/nimcache/stdlib_strutils.o /Users/gseethar/Documents/Code/GitHub/Learning/nim/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Slice90851 Slice90851;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Valueerror3446 Valueerror3446;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell48505 Cell48505;
typedef struct Cellseq48521 Cellseq48521;
typedef struct Gcheap51018 Gcheap51018;
typedef struct Gcstack51016 Gcstack51016;
typedef struct Memregion30686 Memregion30686;
typedef struct Smallchunk30640 Smallchunk30640;
typedef struct Llchunk30680 Llchunk30680;
typedef struct Bigchunk30642 Bigchunk30642;
typedef struct Intset30614 Intset30614;
typedef struct Trunk30610 Trunk30610;
typedef struct Avlnode30684 Avlnode30684;
typedef struct Gcstat51014 Gcstat51014;
typedef struct Cellset48517 Cellset48517;
typedef struct Pagedesc48513 Pagedesc48513;
typedef struct Basechunk30638 Basechunk30638;
typedef struct Freecell30630 Freecell30630;
struct  Slice90851  {
NI a;
NI b;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3446  {
  Exception Sup;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell48505  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48521  {
NI len;
NI cap;
Cell48505** d;
};
typedef Smallchunk30640* TY30701[512];
typedef Trunk30610* Trunkbuckets30612[256];
struct  Intset30614  {
Trunkbuckets30612 data;
};
struct  Memregion30686  {
NI minlargeobj;
NI maxlargeobj;
TY30701 freesmallchunks;
Llchunk30680* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30642* freechunkslist;
Intset30614 chunkstarts;
Avlnode30684* root;
Avlnode30684* deleted;
Avlnode30684* last;
Avlnode30684* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat51014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset48517  {
NI counter;
NI max;
Pagedesc48513* head;
Pagedesc48513** data;
};
struct  Gcheap51018  {
Gcstack51016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48521 zct;
Cellseq48521 decstack;
Cellseq48521 tempstack;
NI recgclock;
Memregion30686 region;
Gcstat51014 stat;
Cellset48517 marked;
Cellseq48521 additionalroots;
};
struct  Gcstack51016  {
Gcstack51016* prev;
Gcstack51016* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30640  {
  Basechunk30638 Sup;
Smallchunk30640* next;
Smallchunk30640* prev;
Freecell30630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30680  {
NI size;
NI acc;
Llchunk30680* next;
};
struct  Bigchunk30642  {
  Basechunk30638 Sup;
Bigchunk30642* next;
Bigchunk30642* prev;
NI align;
NF data;
};
typedef NI TY30619[8];
struct  Trunk30610  {
Trunk30610* next;
NI key;
TY30619 bits;
};
typedef Avlnode30684* TY30691[2];
struct  Avlnode30684  {
TY30691 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc48513  {
Pagedesc48513* next;
NI key;
TY30619 bits;
};
struct  Freecell30630  {
Freecell30630* next;
NI zerofield;
};
static N_INLINE(NIM_BOOL, contains_107475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_107485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22601_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_107650_1689653243)(Slice90851 s0, NI value0);
N_NIMCALL(NF, round_107661_1009420244)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_107691_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_107701_1689653243)(NF* x0, NF y0);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell48505*, usrtocell_52640_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53801_1689653243)(Cell48505* c0);
N_NOINLINE(void, addzct_52617_1689653243)(Cellseq48521* s0, Cell48505* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
STRING_LITERAL(TMP178, "invalid integer: ", 17);
extern TFrame* frameptr_19836_1689653243;
extern TNimType NTI24425; /* ref ValueError */
extern TNimType NTI3446; /* ValueError */
extern Gcheap51018 gch_51058_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19836_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19836_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19836_1689653243;
	frameptr_19836_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22601_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19836_1689653243 = (*frameptr_19836_1689653243).prev;
}

static N_INLINE(NI, find_107485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_107519_1689653243;
		NI i_107532_1689653243;
		i_107519_1689653243 = (NIM_CHAR)0;
		nimln(1966, "system.nim");
		i_107532_1689653243 = ((NI) 0);
		{
			nimln(1967, "system.nim");
			while (1) {
				NI TMP156;
				NI TMP157;
				if (!(i_107532_1689653243 < a0Len0)) goto LA3;
				nimln(1968, "system.nim");
				if ((NU)(i_107532_1689653243) >= (NU)(a0Len0)) raiseIndexError();
				i_107519_1689653243 = a0[i_107532_1689653243];
				nimln(2191, "system.nim");
				{
					if (!((NU8)(i_107519_1689653243) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2192, "system.nim");
				TMP156 = addInt(result0, ((NI) 1));
				result0 = (NI)(TMP156);
				nimln(1969, "system.nim");
				TMP157 = addInt(i_107532_1689653243, ((NI) 1));
				i_107532_1689653243 = (NI)(TMP157);
			} LA3: ;
		}
	}
	nimln(2193, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_107475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2198, "system.nim");
	nimln(346, "system.nim");
	nimln(347, "system.nim");
	nimln(2198, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_107485_1689653243(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_107650_1689653243)(Slice90851 s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1093, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_107691_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3324, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_107701_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3314, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	memcpy(((NCSTRING) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((NCSTRING) ((*src0).data)), (NI)((*src0).Sup.len + ((NI) 1)));
	(*dest0).Sup.len += (*src0).Sup.len;
}

static N_INLINE(Cell48505*, usrtocell_52640_1689653243)(void* usr0) {
	Cell48505* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell48505*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell48505*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell48505))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53801_1689653243)(Cell48505* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_52617_1689653243((&gch_51058_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell48505* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_52640_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell48505* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_52640_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_53801_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0) {
	NI result0;
	NI L0;
	nimfr("parseInt", "strutils.nim")
	result0 = (NI)0;
	L0 = npuParseInt(s0, (&result0), ((NI) 0));
	{
		NIM_BOOL LOC3;
		Valueerror3446* e_104664_4286263276;
		NimStringDesc* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !((L0 == (s0 ? s0->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L0 == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_104664_4286263276 = (Valueerror3446*)0;
		e_104664_4286263276 = (Valueerror3446*) newObj((&NTI24425), sizeof(Valueerror3446));
		(*e_104664_4286263276).Sup.Sup.m_type = (&NTI3446);
		LOC7 = (NimStringDesc*)0;
		LOC7 = rawNewString(s0->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP178));
appendString(LOC7, s0);
		asgnRefNoCycle((void**) (&(*e_104664_4286263276).Sup.message), LOC7);
		raiseException((Exception*)e_104664_4286263276, "ValueError");
	}
	LA5: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

